from PySide6.QtCore import QSize


APP_TITLE = "档案管理"
WINDOW_SIZE = (1180, 740)
SIDEBAR_WIDTH = 220
PHOTO_GRID_COLUMNS = 3
PHOTO_GRID_ROWS = 2
PHOTO_CARD_WIDTH = 280
PHOTO_CARD_HEIGHT = 250
PHOTO_CARD_PREVIEW_HEIGHT = 180
PHOTO_CARD_TITLE_HEIGHT = 28
PHOTO_CARD_META_HEIGHT = 14
FONT_FAMILY = "Microsoft YaHei UI"
FONT_STACK = '"Microsoft YaHei UI", "Segoe UI Variable", "Segoe UI"'
BASE_FONT_POINT_SIZE = 11
TRANSITION_ANIMATION_MS = 460
DETAIL_IMAGE_FINAL_SIZE = QSize(440, 420)
DETAIL_IMAGE_SLIDE_OFFSET = 220

COLOR_BG = "#f5e3b6"
COLOR_BG_GRADIENT_START = "#fff4d4"
COLOR_BG_GRADIENT_END = "#e7c982"
COLOR_SURFACE = "#fff7df"
COLOR_SURFACE_2 = "#fff1c7"
COLOR_SURFACE_3 = "#ffe6a3"
COLOR_TEXT = "#111111"
COLOR_MUTED = "#2b2113"
COLOR_BORDER = "#9a7a28"
COLOR_PRIMARY = "#ffe6a3"
COLOR_PRIMARY_HOVER = "#f4cf72"
COLOR_SUCCESS = "#fff1c7"
COLOR_SUCCESS_HOVER = "#f4cf72"
COLOR_DANGER = "#dc2626"
